// <auto-generated />
using System;
using Bolao.Infra.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bolao.Infra.Migrations
{
    [DbContext(typeof(BolaoContext))]
    [Migration("20190317145743_bolao3")]
    partial class bolao3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bolao.Domain.Domains.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("FisrtName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Bolao.Domain.Domains.User", b =>
                {
                    b.OwnsOne("Bolao.Domain.ObjectValue.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserIdUser");

                            b1.Property<int>("CascadeMode");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasMaxLength(80);

                            b1.HasKey("UserIdUser");

                            b1.ToTable("User");

                            b1.HasOne("Bolao.Domain.Domains.User")
                                .WithOne("Email")
                                .HasForeignKey("Bolao.Domain.ObjectValue.Email", "UserIdUser")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
