// <auto-generated />
using Bolao.Infra.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace Bolao.Infra.Migrations
{
	[DbContext(typeof(BolaoContext))]
    partial class BolaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bolao.Domain.Domains.MegaSenaBetNumber", b =>
                {
                    b.Property<int>("IdMegaSenaBetNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdTicket");

                    b.Property<string>("Number");

                    b.HasKey("IdMegaSenaBetNumber");

                    b.ToTable("MegaSenaBetNumber");
                });

            modelBuilder.Entity("Bolao.Domain.Domains.MegaSenaLottery", b =>
                {
                    b.Property<int>("IdMegaSenaLoterry")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LoterryDate");

                    b.HasKey("IdMegaSenaLoterry");

                    b.ToTable("MegaSenaLottery");
                });

            modelBuilder.Entity("Bolao.Domain.Domains.MegaSenaLotteryNumber", b =>
                {
                    b.Property<int>("IdMegaSenaNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdMegaSenaLoterry");

                    b.Property<string>("Number");

                    b.HasKey("IdMegaSenaNumber");

                    b.ToTable("MegaSenaLotteryNumber");
                });

            modelBuilder.Entity("Bolao.Domain.Domains.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime>("EndDateBet");

                    b.Property<int>("IdTypeBet");

                    b.Property<Guid>("IdUser");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("StartDateBet");

                    b.HasKey("IdTicket");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Bolao.Domain.Domains.TypeBet", b =>
                {
                    b.Property<int>("IdTypeBet")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("IdTypeBet");

                    b.ToTable("TypeBet");
                });

            modelBuilder.Entity("Bolao.Domain.Domains.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("FisrtName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Bolao.Domain.Domains.User", b =>
                {
                    b.OwnsOne("Bolao.Domain.ObjectValue.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserIdUser");

                            b1.Property<int>("CascadeMode");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasMaxLength(80);

                            b1.HasKey("UserIdUser");

                            b1.ToTable("User");

                            b1.HasOne("Bolao.Domain.Domains.User")
                                .WithOne("Email")
                                .HasForeignKey("Bolao.Domain.ObjectValue.Email", "UserIdUser")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
