//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolao.CrossCutting.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bolao.CrossCutting.Messages.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua conta ainda não foi ativada..
        /// </summary>
        public static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este e-mail já existe em nossa base de dados..
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um problema interno com o servidor. Entre em contato com o Administrador do sistema caso o problema persista..
        /// </summary>
        public static string ErrorGeneric400 {
            get {
                return ResourceManager.GetString("ErrorGeneric400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha inválido..
        /// </summary>
        public static string InvalidAuth {
            get {
                return ResourceManager.GetString("InvalidAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativação inválida..
        /// </summary>
        public static string InvalidConfirmToken {
            get {
                return ResourceManager.GetString("InvalidConfirmToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail {0} inválido..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} inválido..
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido..
        /// </summary>
        public static string InvalidForgotPasswordToken {
            get {
                return ResourceManager.GetString("InvalidForgotPasswordToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de números inválidos..
        /// </summary>
        public static string InvalidLimitNumbers {
            get {
                return ResourceManager.GetString("InvalidLimitNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número inválido..
        /// </summary>
        public static string InvalidNumberLottery {
            get {
                return ResourceManager.GetString("InvalidNumberLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de números informados é inválido..
        /// </summary>
        public static string LimiteLotteryResultInvalid {
            get {
                return ResourceManager.GetString("LimiteLotteryResultInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogo não encontrado..
        /// </summary>
        public static string LotteryNotFound {
            get {
                return ResourceManager.GetString("LotteryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Números duplicados..
        /// </summary>
        public static string NumberBetDuplicated {
            get {
                return ResourceManager.GetString("NumberBetDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas estão diferentes..
        /// </summary>
        public static string PasswordNotTheSame {
            get {
                return ResourceManager.GetString("PasswordNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} deve conter no mínimo {1} e máximo {2} caracteres..
        /// </summary>
        public static string RangeLength {
            get {
                return ResourceManager.GetString("RangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} obrigatório..
        /// </summary>
        public static string RequiredFieldX {
            get {
                return ResourceManager.GetString("RequiredFieldX", resourceCulture);
            }
        }
    }
}
